env:
  global:
  - GIT_DEPLOY_DIR=public
  - GIT_DEPLOY_BRANCH=master
  - GIT_DEPLOY_USERNAME="Saddam H"
  - GIT_DEPLOY_EMAIL=thedevsaddam@gmail.com
  - secure: sXl3sl/1pX15668AdHEejLMK7kQd8uZgTmO+BCKQh2YGV2zX4+9uUkhSUjKCR3RgYCdvDgEleitg6Q8NXW6L7OwhryVXHBOPHScjn4E1+8mwFxBtGYzihrBjDs8CzeV74LQozmUswt2s+atTPIUvnt/1ny2T5Hkb7WCSLXfgzObqGLMtwmFgXlXdVjqC6CRwCwTJqhWoxI9ykGxmfuZmtB7zES0g7wkqApmLsnGOemJ2OGhVf4rCbkdbx6uey07y5ofYRPrgrWILn64Gn8adGWmt3UGKXW9c07moOg3O8+Bc/2NsSTkf+Vg+5ZV14YQnhb5w64tQJvDl0+qX/CH7y18g31GZ/DQkDRMVmF3MbCH6281YegPv6NQAyDGuUTmYQSsL25B6zBJeSecwcDRtJz6XIjTdFCjk8ndhOP17Y4/qWECQN88cK6I8Eymx0blEc4OhS5Q8pDnYbC1UrzvCHA1ex4aBGH+KdCJWOIox+AfEfcrCdcDpIljsZGRfgTf3ElZ6K6rw2m4utTxi5k8WhYrxPnDIch1CVhEWgBksk2/aIQpR8utw1JcKHl9R9Lpktl2AVJwXAYHl5lt1OmdHtdllGVGj1EcayepImnbdNJA6AyBHKo/V5+M0xi0X4zJyXSLjiaZCXcz+1utCLX2w1STCH7Anrv0Swt5ROG1XUFU=
branches:
  only:
  - sources
before_install:
- chmod +x hugo/hugo
install:
- rm -rf public || exit 0
script:
- hugo/hugo
after_success:
- cp .travis.yml public
- bash deploy.sh
